# vim: ft=toml
# Work in progress, those values are not implemented in the app.

[Display]
# Display names for rotation. If omitted or empty, all displays rotate.
enabled = [ "eDP" ]

# Displays to ignore. Useful when ... (when???)
# @TODO (undg) 2024-04-16: decide if can be deleted
#ignored = []

[Input]
# Use `autorotate list` to find input names.

# Input names for rotation. Defaults to all if omitted or empty.
#enabled = []

# Devices that will not rotate.
ignored = [
    "Razer Razer Basilisk X HyperSpeed", # mouse
    "Virtual core XTEST pointer", # barrier/synergy
]

[Keyboard]
# Keyboard names to controll, typicaly only your laptop's keyboard.
name = ["AT Translated Set 2 keyboard"]
# Conditions to disable keyboard:
disable_on_landscape=true
disable_on_landscapeInvert=false
disable_on_portrait=false
disable_on_portraitInvert=false
